import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import HomeMobileSidebar from '@/components/layout/home-mobile-sidebar';
import { ProductSidebarProvider } from '@/context/product-sidebar-context';
import ProductSidebar from '@/components/layout/product-sidebar';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-open-sans'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${openSans.variable} antialiased`}>
        <NuqsAdapter>
          <ProductSidebarProvider>
            <Toaster />
            <SidebarProvider defaultOpen={false}>
              <HomeMobileSidebar />
              <SidebarInset>{children}</SidebarInset>
            </SidebarProvider>
            <ProductSidebar />
          </ProductSidebarProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
