import {
  IconActivity,
  IconAlertTriangle,
  IconArrowRight,
  IconBrandGithub,
  IconBrandTwitter,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClipboardList,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconHome,
  IconLayoutKanban,
  // IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX
} from '@tabler/icons-react';
import {
  BookOpenText,
  GraduationCap,
  ShieldCheck,
  TriangleAlert,
  Truck,
  AlignLeft,
  ChartPie,
  ReceiptText,
  Wifi,
  Rows3,
  Ticket,
  BookText
} from 'lucide-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconHome,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  question: IconClipboardList,
  exercise: IconActivity,
  blog: BookOpenText,
  file: IconFile,
  shield: ShieldCheck,
  alert: TriangleAlert,
  truck: Truck,
  graduationCap: GraduationCap,
  AlignLeft: AlignLeft,
  ChartPie: ChartPie,
  ReceiptText: ReceiptText,
  Wifi: Wifi,
  Rows3: Rows3,
  Ticket: Ticket,
  BookText: BookText
};
export const IconsString = {
  eye: 'ic:baseline-remove-red-eye',
  eyeOff: 'tabler:eye-off',
  circleDot: 'fa-regular:dot-circle',
  completedCheck: 'pajamas:check',
  plus: 'ic:baseline-plus',
  bin: 'ri:delete-bin-6-line',
  leftArrow: 'mdi-light:arrow-left',
  radioButtonCircleDot: 'stash:circle-dot-solid',
  upload: 'icon-park-solid:upload',
  viewEye: 'formkit:eye',
  downArrow: 'ri:arrow-down-line',
  upArrow: 'ri:arrow-up-line',
  contactInfo: 'fluent-mdl2:contact-info',
  clockFill: 'iconamoon:clock-fill',
  lineXCircleFilled: 'ic:outline-remove-circle',
  tickCircle: 'mdi:tick-circle',
  plusCircle: 'ep:circle-plus-filled',
  keyboardRightArrow: 'iconamoon:arrow-right-2-bold',
  keyboardLeftArrow: 'iconamoon:arrow-left-2-bold',
  keyboardDownArrow: 'ep:arrow-down',
  onboaringUpload: 'material-symbols:upload-file-outline',
  outlineCircleTick: 'charm:circle-tick',
  clockCountDownFill: 'ph:clock-countdown-fill',
  timer: 'ph:timer-fill',
  infoFill: 'material-symbols:info-outline',
  link: 'ant-design:link-outlined',
  bag: 'bytesize:bag',
  personId: 'fa-regular:id-badge',
  folder: 'ph:folder-light',
  checkedList: 'icon-park-outline:list',
  roadTest: 'system-uicons:list-add',
  addList: 'ph:list-plus',
  fileSearch: 'ci:file-search',
  edit: 'pepicons-pop:pen',
  truck: 'fa7-regular:truck',
  folderUser: 'ph:folder-user',
  timericon: 'ph:timer',
  triangleAlert: 'eva:alert-triangle-outline',
  sent: 'entypo:paper-plane',
  polygon: 'akar-icons:triangle-fill',
  heartOutlined: 'mdi:heart-outline',
  fileView: 'hugeicons:file-view',
  deliveryVan: 'material-symbols:delivery-truck-speed-outline-rounded'
};
